# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

require 'fileutils'

MAX_CPUS   = 1
MAX_MEMORY = 1024
SERVER_NAME = "pruiz-caS"
WORKER_NAME = "pruiz-caSW"
SERVER_IP  = "192.168.56.110"
WORKER_IP  = "192.168.56.111"
VM_PROVIDER = "virtualbox"


if Dir.exist?("/goinfre/pruiz-ca")
  # Add this to zshrc:
  # export VAGRANT_HOME = "/goinfre/pruiz-ca/.vagrant.d"
  # export VAGRANT_DOTFILE_PATH = "/goinfre/pruiz-ca/.vagrant"

  system("VBoxManage", "setproperty", "machinefolder", "/goinfre/pruiz-ca/VirtualBox VMs")
  FileUtils.mkdir_p("/goinfre/pruiz-ca/VirtualBox VMs")
end

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.

  unless File.exist?(".token")
    token = SecureRandom.hex(32)
    File.write(".token", token)
    puts "Generated new K3S token and saved to .token"
  end

  K3S_TOKEN = File.read(".token").strip

  config.vm.box = "bento/debian-13"
  config.vm.box_version = "202510.26.0"
  config.ssh.insert_key = true

  # Server
  config.vm.define SERVER_NAME do |server|
    server.vm.hostname = SERVER_NAME
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.provider VM_PROVIDER do |vb|
      vb.name = SERVER_NAME
      vb.memory = MAX_MEMORY
      vb.cpus = MAX_CPUS
      vb.gui = false
    end
    server.vm.provision "shell",
      env: {
        'K3S_TOKEN' => K3S_TOKEN,
        'INSTALL_K3S_EXEC' => 'server ',
      },
      inline: <<-SHELL
        echo 'Provisioning server...'
        sudo ufw disable || true
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server " sh -
      SHELL
  end

  # Agent
  config.vm.define WORKER_NAME do |worker|
    worker.vm.hostname = WORKER_NAME
    worker.vm.network "private_network", ip: WORKER_IP
    worker.vm.provider VM_PROVIDER do |vb|
      vb.name = WORKER_NAME
      vb.memory = MAX_MEMORY
      vb.cpus = MAX_CPUS
      vb.gui = false
    end
    worker.vm.provision "shell",
      env: {
        'INSTALL_K3S_EXEC' => 'agent ',
        'K3S_URL' => "https://#{SERVER_IP}:6443",
        'K3S_TOKEN' => K3S_TOKEN,
      },
      inline: <<-SHELL
        echo 'Provisioning worker...'
        curl -sfL https://get.k3s.io | sh -
      SHELL
  end

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Disable the default share of the current code directory. Doing this
  # provides improved isolation between the vagrant box and your host
  # by making sure your Vagrantfile isn't accessible to the vagrant box.
  # If you use this you may want to enable additional shared subfolders as
  # shown above.
  # config.vm.synced_folder ".", "/vagrant", disabled: true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
